# Example mise.toml file
# Place this in your project root

[tasks.hello]
run = "echo Hello."
description = "say hello at terminal"

[tasks.see-you]
run = "echo see you."
description = "say see you at terminal"

